apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    cce/appgroup: wordpress
    name: wordpress
  name: wordpress
  namespace: default
spec:
  replicas: 1
  selector:
    cce/appgroup: wordpress
    name: wordpress
  template:
    metadata:
      labels:
        cce/appgroup: wordpress
        name: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: 192.168.100.244:8635
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: Huawei@201803
        image: 100.125.0.24:6443/ocb0001686/hellonode:latest
        imagePullPolicy: Always
        name: wordpress
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: myregistry
      restartPolicy: Always