apiVersion: v1
kind: Service
metadata:
  labels:
    cce/appgroup: wordpress
    name: wordpress
  name: wordpress
  namespace: default
spec:
  ports:
  - name: wordpress
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    cce/appgroup: wordpress
    name: wordpress
  type: NodePort